### ISSUE TITLE
Support for password generation?

### ISSUE THREAD

**Issue by woodruffw** [1Password/password-rules-parser#15]
Hi there! First of all, thanks for making this crate: I think Apple's password description DSL is very neat, and I'm glad to see that 1Password has already done the valuable work of making a high-quality Rust interface for their password rules :slightly_smiling_face: 

This issue is a potential feature request: is there upstream interest in password *generation* support? In other words: would it be okay for this crate to grow functionality for generating passwords that are compatible with a given ruleset?

If so, I'm happy to try and contribute that functionality -- it's something I'd like to use as a potential downstream consumer of this crate. Otherwise, no problem at all: I can understand wanting to keep this crate's APIs small, and this is something I can do independently.

Thanks for your consideration!

**Comment by Scetch** [comment]
Hello @woodruffw! Thanks for your interest in this crate and password rules, we love seeing folks jump on this spec so we can continue to push reliable password generation forward. 😄 

Our intention for this crate is to keep it as small and scoped as possible and as such we'd like to keep it scoped to just the parser and not include any password generation capabilities. 

I'm going to close this issue for now, but we'd be interested to see what you come up with in the password generation space!

**Comment by woodruffw** [comment]
Thank you for the fast response! That makes perfect sense; I'll pursue this independently.
